In [19]:
%run etl.py

STARTING ETL pipeline (to process song_data and log_data)             at 2023-01-28 17:41:24.953750

Start processing song_data JSON files...
Reading song_data files from data/song_data/A/A/A/*.json...
...finished reading song_data in 0:00:00.129615.
Song_data schema:
root
 |-- artist_id: string (nullable = true)
 |-- artist_latitude: double (nullable = true)
 |-- artist_location: string (nullable = true)
 |-- artist_longitude: double (nullable = true)
 |-- artist_name: string (nullable = true)
 |-- duration: double (nullable = true)
 |-- num_songs: long (nullable = true)
 |-- song_id: string (nullable = true)
 |-- title: string (nullable = true)
 |-- year: long (nullable = true)

Songs_table schema:
root
 |-- song_id: string (nullable = true)
 |-- title: string (nullable = true)
 |-- artist_id: string (nullable = true)
 |-- year: long (nullable = true)
 |-- duration: double (nullable = true)

Songs_table examples:
+------------------+-------------------------------------------+------------------+----+---------+
|song_id           |title                                      |artist_id         |year|duration |
+------------------+-------------------------------------------+------------------+----+---------+
|SOMZWCG12A8C13C480|I Didn't Mean To                           |ARD7TVE1187B99BFB1|0   |218.93179|
|SOXVLOJ12AB0189215|Amor De Cabaret                            |ARKRRTF1187B9984DA|0   |177.47546|
|SOUDSGM12AC9618304|Insatiable (Instrumental Version)          |ARNTLGG11E2835DDB9|0   |266.39628|
|SOMJBYD12A6D4F8557|Keepin It Real (Skit)                      |ARD0S291187B9B7BF5|0   |114.78159|
|SOYMRWW12A6D4FAB14|The Moon And I (Ordinary Day Album Version)|ARKFYS91187B98E58F|0   |267.7024 |
+------------------+-------------------------------------------+------------------+----+---------+
only showing top 5 rows

Writing songs_table parquet files to DataFrame[song_id: string, title: string, artist_id: string, year: bigint, duration: double]...
...finished writing songs_table in 0:00:02.167368.
root
 |-- artist_id: string (nullable = true)
 |-- name: string (nullable = true)
 |-- location: string (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)

+------------------+---------------------+---------------------------+--------+---------+
|artist_id         |name                 |location                   |latitude|longitude|
+------------------+---------------------+---------------------------+--------+---------+
|ARNTLGG11E2835DDB9|Clp                  |                           |null    |null     |
|ARKRRTF1187B9984DA|Sonora Santanera     |                           |null    |null     |
|AR10USD1187B99F3F1|Tweeterfriendly Music|Burlington, Ontario, Canada|null    |null     |
|AR7G5I41187FB4CE6C|Adam Ant             |London, England            |null    |null     |
|ARKFYS91187B98E58F|Jeff And Sheri Easter|                           |null    |null     |
+------------------+---------------------+---------------------------+--------+---------+
only showing top 5 rows

Writing artists_table parquet files to DataFrame[artist_id: string, name: string, location: string, latitude: double, longitude: double]...
...finished writing artists_table in 0:00:03.319175.
Finished processing song_data in 0:00:05.617446.

Start processing log_data JSON files...
Reading log_data files from data/log_data/*.json...
...finished reading log_data in 0:00:00.014307.
Users_table schema:
root
 |-- user_id: string (nullable = true)
 |-- first_name: string (nullable = true)
 |-- last_name: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- level: string (nullable = true)

Users_table examples:
+-------+----------+---------+------+-----+
|user_id|first_name|last_name|gender|level|
+-------+----------+---------+------+-----+
|     51|      Maia|    Burke|     F| free|
|      7|    Adelyn|   Jordan|     F| free|
|     15|      Lily|     Koch|     F| paid|
|     54|     Kaleb|     Cook|     M| free|
|    101|    Jayden|      Fox|     M| free|
+-------+----------+---------+------+-----+
only showing top 5 rows

Writing users_table parquet files to DataFrame[user_id: string, first_name: string, last_name: string, gender: string, level: string]...
...finished writing users_table in 0:00:01.910044.
Creating timestamp column...
root
 |-- ts: double (nullable = true)
 |-- userId: string (nullable = true)
 |-- level: string (nullable = true)
 |-- song_id: string (nullable = true)
 |-- artist_id: string (nullable = true)
 |-- sessionId: string (nullable = true)
 |-- location: string (nullable = true)
 |-- userAgent: string (nullable = true)
 |-- song: string (nullable = true)
 |-- length: string (nullable = true)
 |-- artist: string (nullable = true)
 |-- timestamp: string (nullable = true)

+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+--------------------+---------+-----------+----------+
|               ts|userId|level|song_id|artist_id|sessionId|            location|           userAgent|                song|   length|     artist| timestamp|
+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+--------------------+---------+-----------+----------+
|1.542241826796E12|    26| free|   null|     null|      583|San Jose-Sunnyval...|"Mozilla/5.0 (X11...|       Sehr kosmisch|655.77751|   Harmonia|1542241826|
|1.542242481796E12|    26| free|   null|     null|      583|San Jose-Sunnyval...|"Mozilla/5.0 (X11...|     The Big Gundown|260.07465|The Prodigy|1542242481|
|1.542242741796E12|    26| free|   null|     null|      583|San Jose-Sunnyval...|"Mozilla/5.0 (X11...|            Marry Me|205.45261|      Train|1542242741|
|1.542253449796E12|    61| free|   null|     null|      597|Houston-The Woodl...|"Mozilla/5.0 (Mac...|           Blackbird|218.06975|Sony Wonder|1542253449|
|1.542260935796E12|    80| paid|   null|     null|      602|Portland-South Po...|"Mozilla/5.0 (Mac...|Best Of Both Worl...|289.38404|  Van Halen|1542260935|
+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+--------------------+---------+-----------+----------+
only showing top 5 rows

Creating datetime column...
Log_data + timestamp + datetime + dayofweek columns schema:
root
 |-- ts: double (nullable = true)
 |-- userId: string (nullable = true)
 |-- level: string (nullable = true)
 |-- song_id: string (nullable = true)
 |-- artist_id: string (nullable = true)
 |-- sessionId: string (nullable = true)
 |-- location: string (nullable = true)
 |-- userAgent: string (nullable = true)
 |-- song: string (nullable = true)
 |-- length: string (nullable = true)
 |-- artist: string (nullable = true)
 |-- timestamp: string (nullable = true)
 |-- datetime: string (nullable = true)
 |-- dayofweek: integer (nullable = true)

Log_data + timestamp + datetime + dayofweek columns examples:
+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+--------------------+---------+-----------+----------+--------------------+---------+
|               ts|userId|level|song_id|artist_id|sessionId|            location|           userAgent|                song|   length|     artist| timestamp|            datetime|dayofweek|
+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+--------------------+---------+-----------+----------+--------------------+---------+
|1.542241826796E12|    26| free|   null|     null|      583|San Jose-Sunnyval...|"Mozilla/5.0 (X11...|       Sehr kosmisch|655.77751|   Harmonia|1542241826|2018-11-15 00:30:...|        5|
|1.542242481796E12|    26| free|   null|     null|      583|San Jose-Sunnyval...|"Mozilla/5.0 (X11...|     The Big Gundown|260.07465|The Prodigy|1542242481|2018-11-15 00:41:...|        5|
|1.542242741796E12|    26| free|   null|     null|      583|San Jose-Sunnyval...|"Mozilla/5.0 (X11...|            Marry Me|205.45261|      Train|1542242741|2018-11-15 00:45:...|        5|
|1.542253449796E12|    61| free|   null|     null|      597|Houston-The Woodl...|"Mozilla/5.0 (Mac...|           Blackbird|218.06975|Sony Wonder|1542253449|2018-11-15 03:44:...|        5|
|1.542260935796E12|    80| paid|   null|     null|      602|Portland-South Po...|"Mozilla/5.0 (Mac...|Best Of Both Worl...|289.38404|  Van Halen|1542260935|2018-11-15 05:48:...|        5|
+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+--------------------+---------+-----------+----------+--------------------+---------+
only showing top 5 rows

Time_table schema:
root
 |-- datetime: string (nullable = true)
 |-- start_time: string (nullable = true)
 |-- hour: integer (nullable = true)
 |-- day: integer (nullable = true)
 |-- week: integer (nullable = true)
 |-- month: integer (nullable = true)
 |-- year: integer (nullable = true)
 |-- weekday: integer (nullable = true)

Time_table examples:
+--------------------+--------------------+----+---+----+-----+----+-------+
|            datetime|          start_time|hour|day|week|month|year|weekday|
+--------------------+--------------------+----+---+----+-----+----+-------+
|2018-11-15 15:37:...|2018-11-15 15:37:...|  15| 15|  46|   11|2018|      5|
|2018-11-15 17:42:...|2018-11-15 17:42:...|  17| 15|  46|   11|2018|      5|
|2018-11-21 04:23:...|2018-11-21 04:23:...|   4| 21|  47|   11|2018|      4|
|2018-11-21 08:52:...|2018-11-21 08:52:...|   8| 21|  47|   11|2018|      4|
|2018-11-21 11:42:...|2018-11-21 11:42:...|  11| 21|  47|   11|2018|      4|
+--------------------+--------------------+----+---+----+-----+----+-------+
only showing top 5 rows

Writing time_table parquet files to DataFrame[datetime: string, start_time: string, hour: int, day: int, week: int, month: int, year: int, weekday: int]...
...finished writing time_table in 0:00:03.727848.
Reading song_data files from data/song_data/A/A/A/*.json...
Joining log_data and song_data df s...
...finished joining song_data and log_data dfs.
Joined song_data + log_data schema:
root
 |-- ts: double (nullable = true)
 |-- userId: string (nullable = true)
 |-- level: string (nullable = true)
 |-- song_id: string (nullable = true)
 |-- artist_id: string (nullable = true)
 |-- sessionId: string (nullable = true)
 |-- location: string (nullable = true)
 |-- userAgent: string (nullable = true)
 |-- song: string (nullable = true)
 |-- length: string (nullable = true)
 |-- artist: string (nullable = true)
 |-- timestamp: string (nullable = true)
 |-- datetime: string (nullable = true)
 |-- dayofweek: integer (nullable = true)
 |-- artist_id: string (nullable = true)
 |-- artist_latitude: double (nullable = true)
 |-- artist_location: string (nullable = true)
 |-- artist_longitude: double (nullable = true)
 |-- artist_name: string (nullable = true)
 |-- duration: double (nullable = true)
 |-- num_songs: long (nullable = true)
 |-- song_id: string (nullable = true)
 |-- title: string (nullable = true)
 |-- year: long (nullable = true)

Joined song_data + log_data examples:
+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+---------+---------+------+----------+--------------------+---------+------------------+---------------+---------------+----------------+-----------+---------+---------+------------------+--------------+----+
|               ts|userId|level|song_id|artist_id|sessionId|            location|           userAgent|     song|   length|artist| timestamp|            datetime|dayofweek|         artist_id|artist_latitude|artist_location|artist_longitude|artist_name| duration|num_songs|           song_id|         title|year|
+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+---------+---------+------+----------+--------------------+---------+------------------+---------------+---------------+----------------+-----------+---------+---------+------------------+--------------+----+
|1.542641764796E12|    49| paid|   null|     null|      724|San Francisco-Oak...|Mozilla/5.0 (Wind...|Ming Tran|154.17424|   Gob|1542641764|2018-11-19 15:36:...|        2|ARXR32B1187FB57099|           null|               |            null|        Gob|209.60608|        1|SOFSOCN12A8C143F5D|Face the Ashes|2007|
+-----------------+------+-----+-------+---------+---------+--------------------+--------------------+---------+---------+------+----------+--------------------+---------+------------------+---------------+---------------+----------------+-----------+---------+---------+------------------+--------------+----+

Extracting columns from joined df...
Songplays_table schema:
root
 |-- start_time: string (nullable = true)
 |-- user_id: string (nullable = true)
 |-- level: string (nullable = true)
 |-- song_id: string (nullable = true)
 |-- artist_id: string (nullable = true)
 |-- session_id: string (nullable = true)
 |-- location: string (nullable = true)
 |-- user_agent: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- month: integer (nullable = true)
 |-- songplay_id: long (nullable = false)

Songplays_table examples:
+--------------------------+-------+-----+------------------+------------------+----------+---------------------------------+-----------------------------------------------------------------+----+-----+-----------+
|start_time                |user_id|level|song_id           |artist_id         |session_id|location                         |user_agent                                                       |year|month|songplay_id|
+--------------------------+-------+-----+------------------+------------------+----------+---------------------------------+-----------------------------------------------------------------+----+-----+-----------+
|2018-11-19 15:36:04.796000|49     |paid |SOFSOCN12A8C143F5D|ARXR32B1187FB57099|724       |San Francisco-Oakland-Hayward, CA|Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0|2018|11   |0          |
+--------------------------+-------+-----+------------------+------------------+----------+---------------------------------+-----------------------------------------------------------------+----+-----+-----------+

Writing songplays_table parquet files to DataFrame[start_time: string, user_id: string, level: string, song_id: string, artist_id: string, session_id: string, location: string, user_agent: string, year: int, month: int, songplay_id: bigint]...
...finished writing songplays_table in 0:00:02.312901.
Finished the ETL pipeline processing.
ALL DONE.
FINISHED ETL pipeline (to process song_data and log_data) at 2023-01-28 17:41:38.538454
TIME: 0:00:13.584704
Running example queries...
Songs_table count: 11
Artists_table count: 11
Users_table count: 98
Time_table count: 6813
Songplays_table count: 1

Joined dataframe schema:
root
 |-- songplay_id: long (nullable = false)
 |-- start_time: string (nullable = true)
 |-- user_id: string (nullable = true)
 |-- song_id: string (nullable = true)
 |-- artist_id: string (nullable = true)
 |-- session_id: string (nullable = true)
 |-- title: string (nullable = true)
 |-- location: string (nullable = true)
 |-- user_agent: string (nullable = true)

Sample Songplays by users:
+-----------+--------------------+-------+------------------+------------------+----------+--------------+--------------------+--------------------+
|songplay_id|          start_time|user_id|           song_id|         artist_id|session_id|         title|            location|          user_agent|
+-----------+--------------------+-------+------------------+------------------+----------+--------------+--------------------+--------------------+
|          0|2018-11-19 15:36:...|     49|SOFSOCN12A8C143F5D|ARXR32B1187FB57099|       724|Face the Ashes|San Francisco-Oak...|Mozilla/5.0 (Wind...|
+-----------+--------------------+-------+------------------+------------------+----------+--------------+--------------------+--------------------+

 "Fine"